# Generated by Django 3.0.3 on 2020-02-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('frequency_in_days', models.IntegerField()),
                ('linkedin_url', models.CharField(max_length=100, null=True)),
                ('twitter_username', models.CharField(max_length=50, null=True)),
                ('phone_number', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Touchpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networking_base.Contact')),
            ],
        ),
    ]
