@startuml
class User {
    id
}

class Contact {
    name
    last_interaction_on
}
User -- Contact

class EmailAddress {
    email
}
Contact --{ EmailAddress

class PhoneNumber {
    phone
}
Contact --{ PhoneNumber

class ContactPlan {
    frequency
}
Contact - ContactPlan

class Reminder {
    due
    skipped_on
}
Contact --{ Reminder
ContactPlan --> Reminder

class Interaction {
    title
    description
    interacted_on
}
Contact --{ Interaction

enum InteractionType {
    Personal
    Video
    Voice
    Text
}
InteractionType -- Interaction

class EmailInteraction {
    gmail_message_id
}
Interaction <|-- EmailInteraction
EmailAddress -- EmailInteraction

class CalendarInteraction {}
Interaction <|-- CalendarInteraction
EmailAddress -- CalendarInteraction

@enduml